apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T03:36:00Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "4602"
  uid: be40133e-d666-4b55-b40f-cb24a8cb2bd8
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.111.243.211
  clusterIPs:
  - 10.111.243.211
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30555
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
